# Generated by Django 5.1.2 on 2024-11-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postion',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='postion',
            new_name='position',
        ),
    ]
